# Generated by Django 5.2.7 on 2025-10-04 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0006_course_is_weekly_course_weekday_and_more'),
        ('customers', '0005_customer_coordinates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Rechnungsnummer')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='Rechnungsdatum')),
                ('due_date', models.DateField(verbose_name='Fälligkeitsdatum')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Betrag')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=19.0, max_digits=5, verbose_name='MwSt. (%)')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('sent', 'Versendet'), ('paid', 'Bezahlt'), ('overdue', 'Überfällig'), ('cancelled', 'Storniert')], default='draft', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='courses.course', verbose_name='Kurs')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customers.customer', verbose_name='Kunde')),
            ],
            options={
                'verbose_name': 'Rechnung',
                'verbose_name_plural': 'Rechnungen',
                'ordering': ['-issue_date'],
            },
        ),
    ]
