# Generated by Django 5.2.7 on 2025-10-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0005_alter_invoice_course_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="is_prevention_certified",
            field=models.BooleanField(
                default=True, verbose_name="Zertifiziert nach § 20 SGB V"
            ),
        ),
    ]
