# Generated by Django 5.2.7 on 2025-10-16 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_alter_invoice_is_prevention_certified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'verbose_name': 'Unternehmenseinstellungen'},
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='is_active',
        ),
    ]
