# Generated by Django 5.2.7 on 2025-10-18 05:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_customerdiscountcode_email_sent_and_more'),
        ('invoices', '0007_alter_companyinfo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Rabattbetrag'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='customers.customerdiscountcode', verbose_name='Rabattcode'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Originalbetrag (vor Rabatt)'),
        ),
    ]
