# Generated by Django 5.2.7 on 2025-11-11 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_alter_invoice_update_fk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyInfo',
        ),
    ]
