# Generated by Django 5.2.8 on 2025-11-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0010_delete_companyinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="email_sent",
            field=models.BooleanField(
                default=False,
                help_text="Wurde die Rechnung per Email versendet?",
                verbose_name="Email versendet",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="email_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Zeitpunkt des Email-Versands",
                null=True,
                verbose_name="Email versendet am",
            ),
        ),
    ]
