# Generated by Django 5.2.7 on 2025-10-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_number', models.CharField(max_length=50, unique=True, verbose_name='Angebotsnummer')),
                ('course_type', models.CharField(choices=[('rueckbildung', 'Rückbildung'), ('pilates', 'Pilates'), ('body-workout', 'Body-Workout'), ('personal-coach', 'Personal Coach'), ('10er-karte', '10er Karte')], max_length=50, verbose_name='Kurstyp')),
                ('title', models.CharField(choices=[('rueckbildung', 'Kräftigendes Beckenbodentraining'), ('pilates', 'Pilates'), ('body-workout', 'Kräftigungstraining für Mamas'), ('personal-coach', 'Personal Coach'), ('10er-karte', '10er Karte')], max_length=200, verbose_name='Titel')),
                ('course_units', models.CharField(blank=True, max_length=100, verbose_name='Anzahl Einheiten')),
                ('course_duration', models.CharField(blank=True, max_length=100, verbose_name='Dauer pro Einheit')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Betrag (Netto)')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='MwSt. (%)')),
                ('is_tax_exempt', models.BooleanField(default=True, verbose_name='Kleinunternehmerregelung (§19 UStG)')),
                ('is_prevention_certified', models.BooleanField(default=False, verbose_name='Zertifiziert nach § 20 SGBV')),
                ('zpp_prevention_id', models.CharField(blank=True, choices=[('KU-BE-ZCURFS', 'Pilates Präsens 2027'), ('KU-BE-XHQ7AR', 'Rückbildung Präsens 2027'), ('KU-BE-SC4KUQ', 'Body-Wrkout Präsens 2027')], max_length=50, verbose_name='ZPP Präventions-ID')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen/Besonderheiten')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Angebot',
                'verbose_name_plural': 'Angebote',
                'ordering': ['-created_at'],
            },
        ),
    ]
