# Generated by Django 5.2.7 on 2025-10-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_remove_offer_is_prevention_certified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='course_duration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dauer pro Einheit'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='course_units',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Anzahl Einheiten'),
        ),
    ]
