# Generated by Django 5.2.7 on 2025-10-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0005_alter_offer_course_duration_alter_offer_course_units"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="course_duration",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Dauer pro Einheit"
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="course_units",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Anzahl Einheiten"
            ),
        ),
    ]
