# Generated by Django 5.2.8 on 2025-12-03 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0010_alter_offer_course_type_alter_offer_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='course_type',
        ),
        migrations.AddField(
            model_name='offer',
            name='format',
            field=models.CharField(blank=True, choices=[('praesenz', 'Präsenz'), ('online', 'Online'), ('hybrid', 'Hybrid')], help_text='Nur für Kurse: Präsenz/Online/Hybrid', max_length=50, null=True, verbose_name='Kurs-Format'),
        ),
        migrations.AddField(
            model_name='offer',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inaktive Angebote werden nicht angezeigt', verbose_name='Aktiv'),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('course', 'Kurs'), ('ticket_10', '10er-Karte'), ('workshop', 'Workshop'), ('seminar', 'Seminar')], default='course', help_text='Ist das ein Kurs, eine 10er-Karte, Workshop, etc.?', max_length=50, verbose_name='Art des Angebots'),
        ),
        migrations.AddField(
            model_name='offer',
            name='ticket_sessions',
            field=models.IntegerField(default=10, help_text='Anzahl der Einheiten auf der Karte (z.B. 10)', verbose_name='Anzahl Einheiten'),
        ),
        migrations.AddField(
            model_name='offer',
            name='ticket_validity_days',
            field=models.IntegerField(default=365, help_text='Wie lange ist die Karte nach Kauf gültig? (z.B. 365 Tage = 1 Jahr)', verbose_name='Gültig für (Tage)'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='course_duration',
            field=models.IntegerField(blank=True, help_text='Dauer einer Kurseinheit in Minuten (nur für Kurse)', null=True, verbose_name='Dauer pro Einheit (Minuten)'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='course_units',
            field=models.IntegerField(blank=True, help_text='Anzahl der Kurseinheiten (nur für Kurse)', null=True, verbose_name='Anzahl Einheiten'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(help_text="Z.B. 'Pilates Kurs' oder '10er-Karte Yoga'", max_length=200, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='zpp_certification',
            field=models.ForeignKey(blank=True, help_text='Nur für ZPP-zertifizierte Kurse', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='offers.zppcertification', verbose_name='ZPP-Zertifizierung'),
        ),
    ]
