# Generated by Django 5.2.7 on 2025-10-04 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0004_customer_archived_at_customer_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Standort-Name')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='Straße')),
                ('house_number', models.CharField(blank=True, max_length=10, verbose_name='Hausnummer')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='PLZ')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Stadt')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Kursort',
                'verbose_name_plural': 'Kursorte',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Kurstitel')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('course_type', models.CharField(choices=[('pilates', 'Pilates'), ('body_workout', 'Body-Workout'), ('rueckbildung', 'Rückbildung'), ('personal_coach', 'Personal Coach')], default='pilates', max_length=20, verbose_name='Kursart')),
                ('special', models.CharField(blank=True, max_length=100, verbose_name='Special (z.B. Winter Special)')),
                ('start_date', models.DateField(verbose_name='Startdatum')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Enddatum')),
                ('max_participants', models.PositiveIntegerField(default=10, verbose_name='Max. Teilnehmer')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('participants', models.ManyToManyField(blank=True, related_name='courses', to='customers.customer', verbose_name='Teilnehmer')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.location', verbose_name='Kursort')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurse',
                'ordering': ['-start_date'],
            },
        ),
    ]
