# Generated by Django 5.2.7 on 2025-10-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_course_course_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Enddatum'),
        ),
    ]
