# Generated by Django 5.2.7 on 2025-11-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0013_course_course_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="course_time",
        ),
        migrations.AddField(
            model_name="course",
            name="end_time",
            field=models.TimeField(
                blank=True,
                help_text="Z.B. 10:00 Uhr",
                null=True,
                verbose_name="Endzeit",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="start_time",
            field=models.TimeField(
                blank=True,
                help_text="Z.B. 10:00 Uhr",
                null=True,
                verbose_name="Startzeit",
            ),
        ),
    ]
