# Generated by Django 5.2.7 on 2025-11-15 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0015_course_zpp_certification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="zpp_certification",
        ),
    ]
