# Generated by Django 5.2.7 on 2025-11-15 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0016_remove_course_zpp_certification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="description",
        ),
        migrations.RemoveField(
            model_name="course",
            name="special",
        ),
    ]
