# Generated by Django 5.2.7 on 2025-11-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0017_remove_course_description_remove_course_special"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="completion_email_sent",
            field=models.BooleanField(
                default=False,
                help_text="Wurde die Kursabschluss-E-Mail an die Teilnehmer versendet?",
                verbose_name="Abschluss-E-Mail versendet",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="completion_email_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Zeitpunkt des Versands der Kursabschluss-E-Mail",
                null=True,
                verbose_name="Abschluss-E-Mail versendet am",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="start_email_sent",
            field=models.BooleanField(
                default=False,
                help_text="Wurde die Kursstart-E-Mail an die Teilnehmer versendet?",
                verbose_name="Start-E-Mail versendet",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="start_email_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Zeitpunkt des Versands der Kursstart-E-Mail",
                null=True,
                verbose_name="Start-E-Mail versendet am",
            ),
        ),
    ]
