# Generated by Django 5.2.7 on 2025-10-04 20:55

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_customer_archived_at_customer_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="coordinates",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326, verbose_name="Koordinaten"
            ),
        ),
    ]
