# Generated by Django 5.2.7 on 2025-10-14 14:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0005_customer_coordinates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerDiscountCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Code"),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percentage", "Prozent"), ("fixed", "Fester Betrag")],
                        default="percentage",
                        max_length=20,
                        verbose_name="Rabatt-Typ",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Rabattwert"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("birthday", "Geburtstag"),
                            ("course_completed", "Kurs abgeschlossen"),
                            ("referral", "Empfehlung"),
                            ("loyalty", "Treueprämie"),
                            ("other", "Sonstiges"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="Grund",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beschreibung"),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Gültig von"
                    ),
                ),
                ("valid_until", models.DateTimeField(verbose_name="Gültig bis")),
                (
                    "is_used",
                    models.BooleanField(default=False, verbose_name="Verwendet"),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verwendet am"
                    ),
                ),
                (
                    "minimum_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional: Mindestbestellwert",
                        max_digits=10,
                        null=True,
                        verbose_name="Mindestbetrag",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Erstellt von",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discount_codes",
                        to="customers.customer",
                        verbose_name="Kunde",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rabattcode",
                "verbose_name_plural": "Rabattcodes",
                "ordering": ["-created_at"],
            },
        ),
    ]
