# Generated by Django 5.2.7 on 2025-10-14 14:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0006_customerdiscountcode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerdiscountcode",
            name="minimum_amount",
        ),
        migrations.AlterField(
            model_name="customerdiscountcode",
            name="valid_from",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Gültig von"
            ),
        ),
        migrations.AlterField(
            model_name="customerdiscountcode",
            name="valid_until",
            field=models.DateField(verbose_name="Gültig bis"),
        ),
    ]
