# Generated by Django 5.2.7 on 2025-10-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0008_customerdiscountcode_email_sent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerdiscountcode",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Storniert am"
            ),
        ),
        migrations.AddField(
            model_name="customerdiscountcode",
            name="cancelled_reason",
            field=models.TextField(blank=True, verbose_name="Stornierungsgrund"),
        ),
        migrations.AddField(
            model_name="customerdiscountcode",
            name="is_cancelled",
            field=models.BooleanField(default=False, verbose_name="Storniert"),
        ),
    ]
