# Generated by Django 5.2.8 on 2025-11-22 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_customerdiscountcode_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdiscountcode',
            name='valid_from',
            field=models.DateField(default=datetime.date.today, verbose_name='Gültig von'),
        ),
    ]
