# Generated by Django 5.2.7 on 2025-11-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('street', models.CharField(max_length=200, verbose_name='Straße')),
                ('house_number', models.CharField(max_length=10, verbose_name='Hausnummer')),
                ('postal_code', models.CharField(max_length=10, verbose_name='PLZ')),
                ('city', models.CharField(max_length=100, verbose_name='Stadt')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('tax_number', models.CharField(max_length=50, verbose_name='Steuernummer')),
                ('bank_name', models.CharField(max_length=200, verbose_name='Bankname')),
                ('iban', models.CharField(max_length=34, verbose_name='IBAN')),
                ('bic', models.CharField(max_length=11, verbose_name='BIC')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Unternehmenseinstellungen',
            },
        ),
    ]
