# Generated by Django 5.2.7 on 2025-11-11 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_transfer_company_info'),
    ]

    operations = [
    ]
